version: "3.1"
services:
  mariadb:
    image: mariadb:10.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword123456!
      MYSQL_DATABASE: dev_mautic
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: mautic/mautic:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html:cached
  redis:
    image: redis
volumes:
  db_data:
