version: "3.1"
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperPassword123456!
      MYSQL_DATABASE: dev_mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: mautic/mautic:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file: .env
    volumes:
      - .:/var/www/html
  redis:
    image: redis
volumes:
  db_data:
