name: Mautic tests and validations

on:
  push:
    branches:
      - '[0-9].*'
  pull_request:
  schedule:
    # Run every day at 10:45 AM UTC to discover potential issues with dependencies like PHP updates etc.
    - cron: '45 10 * * *'

jobs:
  phpunit:
    # We don't want the scheduled jobs to run on forks of Mautic
    if: (github.event_name == 'schedule' && github.repository_owner == 'mautic') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4']
        db-types: ['mariadb']
  
    name: PHPUnit ${{ matrix.php-versions }} ${{ matrix.db-types }}

    services:
      mariadb:
        image: mariadb:10.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mautictest
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
      # Codecov needs access to previous commits, so we add fetch-depth: 0
      with:
        fetch-depth: 0
    
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
        coverage: pcov
        ini-values: pcov.directory=., pcov.exclude="~tests|themes|vendor~"
    
    - name: Set SYMFONY_ENV to test
      run: echo "SYMFONY_ENV=test" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        composer validate
        composer install --prefer-dist --no-progress --no-suggest
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Temp install Mautic first due to failing tests
      env:
        mysql_port: ${{ job.services.mysql.ports[3306] }}
        mariadb_port: ${{ job.services.mariadb.ports[3306] }}
      run: |
        export DB_PORT_STRING="${{ matrix.db-types }}_port"
        export DB_PORT=${!DB_PORT_STRING}

        env
        cp ./.github/ci-files/local.php ./app/config/local.php
        php bin/console mautic:install --force http://localhost

    - name: Run tests - database = ${{ matrix.db-types }}
      run: |
        export DB_PORT_STRING="${{ matrix.db-types }}_port"
        export DB_PORT=${!DB_PORT_STRING}

        if [[ "${{ matrix.php-versions }}" == "7.4" ]] && [[ "${{ matrix.db-types }}" == "mysql" ]]; then
          composer test -- --coverage-clover=coverage.xml
        else
          composer test
        fi
      env:
        mysql_port: ${{ job.services.mysql.ports[3306] }}
        mariadb_port: ${{ job.services.mariadb.ports[3306] }}
